### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by Ceceu** [Stazer/Crawler#1]
Hello,
thanks and congrats for the framework.

Could you provide a simple Quick Start? For example, a simple Crawler like showed in:

https://www.example-code.com/vcpp/spider_simpleCrawler.asp

Thank you so much.

**Comment by Stazer** [comment]
Hi,
you can find two examples of using the library here:
https://github.com/Stazer/Crawler/blob/master/Source/LocalLinkDirectory/Main.cpp
https://github.com/Stazer/Crawler/blob/master/Source/Email/Main.cpp

The Application.hpp is very helpful, since it summarizes all methods which can be overriden:
https://github.com/Stazer/Crawler/blob/master/Source/Crawler/Application.hpp

The first one is for fetching all links from a particular website and the second one for reading email addresses from a single website.

If I find some time in the future, I will create a tutorial, refactor the code and add another few features.
Actually the project was created for a college class, therefore the code is very messy.

If you have questions, just let me know!

Best Regards
